
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/smartbookshop
      - JWT_SECRET=your_secret_key_in_production
      - JWT_EXPIRES_IN=1d
    depends_on:
      - mongo
    volumes:
      - ./backend:/app

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
